236 add filemanager that can be used in nmrium
cheminfo/nmr-processing pull request #237
Opened 2023-01-20 13:42 UTC by jobo322

2023-05-30 14:46 UTC, targos commented on package.json
> +    "lodash.omit": "^4.5.0",
Please don't use `lodash.xxx` packages. They haven't been updated since a long time ago.

2023-05-30 14:47 UTC, targos requested changes
Please ping me when this is ready. It's a huge change and I want to review at least a little bit before merge.

2023-05-30 20:52 UTC, jobo322 commented
@targos could you have a look?

2023-05-31 07:35 UTC, targos commented
I will have a look tomorrow with the help of Luc.

2023-06-02 07:12 UTC, lpatiny commented on package.json
> +    "ml-array-xy-equally-spaced": "^1.2.1",
This method should be also available in ml-spectra-processing

2023-06-02 07:18 UTC, lpatiny commented
@jobo322 Everything related to parsing (and the type definition Jcamp, Bruker, ...) should not be in this package but either in the corresponding package (jcampconverter, brukerconverter) or nmr-load-save.

2023-06-02 07:31 UTC, lpatiny commented on src/datum/data1d/filter1d/signalProcessing.ts
> +import * as Filters from 'ml-signal-processing';
We should explicitely import the filters we allow in this method. It will allow to remove many expect-errors

2023-06-02 07:51 UTC, targos commented on package.json
> +    "ml-stat": "^1.3.3",
You can remove this unused dependency.

2023-06-02 14:11 UTC, jobo322 commented on src/datum/data1d/filter1d/signalProcessing.ts
> +import * as Filters from 'ml-signal-processing';
Do you have a list of filters allowed?

2023-06-04 07:23 UTC, targos commented on package.json
> +    "ml-array-xy-equally-spaced": "^1.2.1",
If it's not used, you shouldn't add it to the dependencies

2023-06-05 16:08 UTC, jobo322 commented on src/datum/data1d/filter1d/signalProcessing.ts
> +import * as Filters from 'ml-signal-processing';
it is added dynamically by a drop down menu.

![telegram-cloud-photo-size-2-5471894339648079705-y](https://github.com/cheminfo/nmr-processing/assets/12143935/e8f07cfe-a526-40fb-961a-f034c00998f0)

seems all of them can be used in nmrium, I think this is the reason Hamed add all in one shot.

2023-06-08 16:22 UTC, merged